# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 08:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180701_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_user_following_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='follwers',
            field=models.ManyToManyField(blank=True, related_name='_user_follwers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
