# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 02:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0003_comment_timestampedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gallery.TimeStampedModel')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='gallery.Photo')),
            ],
            bases=('gallery.timestampedmodel',),
        ),
    ]
